# ------------------------------------------------------
# ------------------------------------------------------
# VM settings:
variable "vm_name" { default = "tfvm" }
# https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html
variable "location" {
  default  = "us-west-1"
  nullable = false
}
variable "vm_size" {
  default  = "t2.micro"
  nullable = false
}

variable "image_publisher" {
  default  = "099720109477"
  nullable = false
}
variable "image_name" {
  default  = "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-*"
  nullable = false
}
variable "public_iface" { default = "enX0" }

# Cloud Init settings
variable "init_script_template" { default = "cloud_init.yml.tftpl" }

# SSH settings:
variable "admin_username" { default = "ubuntu" }
variable "ssh_key_pub" { default = "~/.ssh/id_rsa.pub" }
variable "ssh_port" { default = 22 }
# Enable ablility to log into server using ssh
variable "enable_ssh_access" {
  type    = bool
  default = false
}

# Wireguard settings:
variable "wg_port" { default = 51820 }
variable "wg_client_pubkey" { type = string }
variable "wg_psk" {
  type      = string
  sensitive = true
}
# Optional, will be autogenerated by default
variable "wg_server_prikey" {
  type      = string
  sensitive = true
  default   = ""
  nullable  = false
}

# Extra settings
variable "extra_open_ports" {
  type    = set(any)
  default = []
}
variable "extra_packages" {
  type    = set(any)
  default = []
}
variable "extra_commands" {
  type    = set(any)
  default = []
}
variable "forward_ports" {
  type    = bool
  default = false
}

# Unused:
variable "image_version" { default = null }
variable "api_key" { default = null }

# ------------------------------------------------------
# ------------------------------------------------------

provider "aws" {
  region = var.location
  default_tags {
    tags = {
      environment = "TF_Wireguard"
    }
  }
}

resource "aws_key_pair" "tf_keypair" {
  key_name   = "terraform_keypair"
  public_key = file(var.ssh_key_pub)
}

# Latest Ubuntu LTS Image
data "aws_ami" "tf_ami" {
  most_recent = true
  owners      = [var.image_publisher]

  filter {
    name   = "name"
    values = [var.image_name]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_security_group" "tf_sg" {
  name = "terraform_securitygroup"

  # To Allow SSH and WireGuard Transport
  ingress {
    from_port   = -1
    to_port     = -1
    protocol    = "icmp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = var.ssh_port
    to_port     = var.ssh_port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = var.wg_port
    to_port     = var.wg_port
    protocol    = "udp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # Any extra TCP Ports to open
  dynamic "ingress" {
    for_each = var.extra_open_ports
    content {
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_instance" "tf_vm" {
  ami                         = data.aws_ami.tf_ami.id
  instance_type               = var.vm_size
  key_name                    = aws_key_pair.tf_keypair.key_name
  vpc_security_group_ids      = [aws_security_group.tf_sg.id]
  associate_public_ip_address = true

  root_block_device {
    delete_on_termination = true
    volume_size           = 10
    volume_type           = "gp2"
  }

  user_data = templatefile(
    var.init_script_template,
    {
      wg_client_pubkey  = file(var.wg_client_pubkey),
      wg_psk            = file(var.wg_psk),
      wg_server_prikey  = var.wg_server_prikey != "" ? file(var.wg_server_prikey) : "",
      admin_username    = var.admin_username,
      admin_ssh_pubkey  = file(var.ssh_key_pub),
      ssh_port          = var.ssh_port,
      wg_port           = var.wg_port,
      public_iface      = var.public_iface,
      enable_ssh_access = var.enable_ssh_access,
      extra_open_ports  = var.extra_open_ports,
      forward_ports     = var.forward_ports,
      extra_packages    = var.extra_packages,
      extra_commands    = var.extra_commands,
  })

  tags = {
    Name = var.vm_name
  }
}

# Output
output "username" {
  value = var.admin_username
}
output "ip_address" {
  value = aws_instance.tf_vm.public_ip
}
output "ssh_port" {
  value = var.ssh_port
}
output "wg_port" {
  value = var.wg_port
}
